-- Seed the 27 courses from the existing frontend courseMetadata.ts
-- All seeded as 'published' with price=0 (admin can update via CMS)
-- Slugs are URL-safe versions of the titles

INSERT INTO courses (title, slug, category, level, price, status, rating, enrollment_count, certified, color, short_desc) VALUES
('Assessment and Design of Environmental Management Systems', 'assessment-design-environmental-management-systems', 'Sustainability', 'Advanced', 0, 'published', 4.7, 120, true, '#10b981', 'Learn to design and assess environmental management systems per ISO standards.'),
('Electric Wiring and Lighting for Residentials and Commercial Buildings', 'electric-wiring-lighting-residential-commercial', 'Electrical', 'Intermediate', 0, 'published', 4.5, 95, false, '#f59e0b', 'Practical electric wiring and lighting design for residential and commercial applications.'),
('Environmental Law', 'environmental-law', 'Sustainability', 'Intermediate', 0, 'published', 4.3, 80, false, '#10b981', 'Understand legal frameworks governing environmental protection and compliance.'),
('Finite Element Analysis Applications in Structural Engineering', 'finite-element-analysis-structural-engineering', 'Simulation', 'Advanced', 0, 'published', 4.8, 200, true, '#8b5cf6', 'Apply FEA methods to real-world structural engineering problems using simulation software.'),
('Introduction to SimSolid | ALTAIR', 'introduction-simsolid-altair', 'Simulation', 'Beginner', 0, 'published', 4.6, 150, false, '#8b5cf6', 'Get started with ALTAIR SimSolid for fast, accurate structural simulation without meshing.'),
('How to Perform an Environmental Impact Assessment (EIA)', 'how-to-perform-environmental-impact-assessment', 'Sustainability', 'Intermediate', 0, 'published', 4.5, 110, true, '#10b981', 'Step-by-step guide to conducting professional Environmental Impact Assessments.'),
('Introduction to Basic HVAC Systems Fundamentals', 'introduction-basic-hvac-systems-fundamentals', 'MEP Systems', 'Beginner', 0, 'published', 4.4, 175, false, '#f97316', 'Core principles of HVAC systems for engineers and technicians entering the field.'),
('Computational Fluid Dynamics Modeling', 'computational-fluid-dynamics-modeling', 'Fluid Dynamics', 'Advanced', 0, 'published', 4.9, 130, true, '#06b6d4', 'Master CFD modeling techniques for industrial fluid flow and heat transfer problems.'),
('Introduction to Detailed Modeling in HVAC', 'introduction-detailed-modeling-hvac', 'MEP Systems', 'Intermediate', 0, 'published', 4.5, 90, false, '#f97316', 'Advanced HVAC modeling techniques covering detailed system design and simulation.'),
('Life Cycle Assessment for Environmental Systems and Devices', 'life-cycle-assessment-environmental-systems', 'Sustainability', 'Advanced', 0, 'published', 4.6, 75, true, '#10b981', 'Conduct comprehensive life cycle assessments using SimaPro and related tools.'),
('Green Building Rating Systems', 'green-building-rating-systems', 'Sustainability', 'Intermediate', 0, 'published', 4.4, 85, false, '#10b981', 'Understand LEED, BREEAM, and other green building certification frameworks.'),
('MATLAB Programming', 'matlab-programming', 'Programming', 'Intermediate', 0, 'published', 4.7, 220, true, '#ef4444', 'Build engineering applications and automate workflows with MATLAB programming.'),
('Minitab Statistical Analysis', 'minitab-statistical-analysis', 'Programming', 'Intermediate', 0, 'published', 4.5, 160, true, '#ef4444', 'Apply statistical methods to quality control and process improvement using Minitab.'),
('Programming with VBA and Macros', 'programming-vba-macros', 'Programming', 'Beginner', 0, 'published', 4.3, 140, false, '#ef4444', 'Automate Excel and Office workflows with VBA programming and macro development.'),
('Electric Machine Winding Design', 'electric-machine-winding-design', 'Electrical', 'Advanced', 0, 'published', 4.7, 65, true, '#f59e0b', 'Design and analyze electric machine windings for motors and generators.'),
('Geotechnical Investigation Methods', 'geotechnical-investigation-methods', 'Civil Engineering', 'Intermediate', 0, 'published', 4.5, 100, false, '#78716c', 'Field and laboratory methods for geotechnical site investigation and analysis.'),
('Lighting Design Fundamentals', 'lighting-design-fundamentals', 'Electrical', 'Beginner', 0, 'published', 4.4, 115, false, '#f59e0b', 'Principles of professional lighting design for interior and exterior applications.'),
('MATLAB Fundamental', 'matlab-fundamental', 'Programming', 'Beginner', 0, 'published', 4.6, 250, false, '#ef4444', 'Introduction to MATLAB for engineers — scripting, visualization, and numerical computing.'),
('Geotechnical System Simulation & Modeling', 'geotechnical-system-simulation-modeling', 'Civil Engineering', 'Advanced', 0, 'published', 4.6, 70, true, '#78716c', 'Simulate and model geotechnical systems for slope stability, settlement, and foundation design.'),
('Minitab Fundamental', 'minitab-fundamental', 'Programming', 'Beginner', 0, 'published', 4.4, 130, false, '#ef4444', 'Introduction to Minitab for data analysis, statistics, and quality improvement.'),
('Operation Protection and Maintenance of Electric Machines', 'operation-protection-maintenance-electric-machines', 'Electrical', 'Advanced', 0, 'published', 4.7, 80, true, '#f59e0b', 'Advanced techniques for the protection, operation, and maintenance of electric machines.'),
('Selection and Installation of Electric Cables', 'selection-installation-electric-cables', 'Electrical', 'Intermediate', 0, 'published', 4.5, 95, false, '#f59e0b', 'Standards and methods for selecting and installing electric cables in various applications.'),
('SolidWorks – Level 1', 'solidworks-level-1', 'CAD Design', 'Beginner', 0, 'published', 4.8, 300, true, '#3b82f6', 'Foundation SolidWorks course covering 3D modeling, assemblies, and drawings.'),
('Variable Frequency Drives and DC Motors', 'variable-frequency-drives-dc-motors', 'Electrical', 'Intermediate', 0, 'published', 4.6, 88, false, '#f59e0b', 'Understand, program, and maintain variable frequency drives and DC motor systems.'),
('SolidWorks Certification Preparation', 'solidworks-certification-preparation', 'CAD Design', 'Advanced', 0, 'published', 4.9, 180, true, '#3b82f6', 'Intensive preparation for CSWA and CSWP SolidWorks certification exams.'),
('CFD Fluid Dynamics Advanced', 'cfd-fluid-dynamics-advanced', 'Fluid Dynamics', 'Advanced', 0, 'published', 4.8, 95, true, '#06b6d4', 'Advanced computational fluid dynamics for turbulence modeling and multiphase flow.'),
('Project Management for Engineers', 'project-management-engineers', 'Sustainability', 'Intermediate', 0, 'published', 4.5, 145, true, '#10b981', 'Engineering project management methodologies, scheduling, cost control, and risk management.')
ON CONFLICT (slug) DO NOTHING;
